name: AdvancedHunt
version: '4.0.0-SNAPSHOT'
main: de.theredend2000.advancedHunt.Main
api-version: '1.21'
authors: [ GrafterCrafter ]

permissions:
  advancedhunt.help:
    description: Allows access to the help command
    default: true
  advancedhunt.list:
    description: Allows listing collections
    default: true
  advancedhunt.leaderboard:
    description: Allows viewing the leaderboard
    default: true
  advancedhunt.progress:
    description: Allows viewing collection progress
    default: true
  advancedhunt.admin:
    description: Grants all administrative permissions
    default: op
    children:
      advancedhunt.admin.reload: true
      advancedhunt.admin.editor: true
      advancedhunt.admin.collection.rename: true
      advancedhunt.admin.collection.create: true
      advancedhunt.admin.place: true
      advancedhunt.admin.reset: true
      advancedhunt.admin.teleport: true
      advancedhunt.admin.view_finders: true
      advancedhunt.admin.rewards: true
  advancedhunt.admin.rewards:
    description: Allows viewing and editing treasure rewards
    default: op
  advancedhunt.admin.reload:
    description: Allows reloading the plugin
    default: op
  advancedhunt.admin.editor:
    description: Allows opening the collection editor
    default: op
  advancedhunt.admin.collection.rename:
    description: Allows renaming collections
    default: op
  advancedhunt.admin.collection.create:
    description: Allows creating collections
    default: op
  advancedhunt.admin.place:
    description: Allows entering place mode
    default: op
  advancedhunt.admin.reset:
    description: Allows resetting player data
    default: op
  advancedhunt.admin.teleport:
    description: Allows teleporting to treasures
    default: op
  advancedhunt.admin.view_finders:
    description: Allows viewing who found a treasure
    default: op
