name: AdvancedHunt
version: '3.1.2-SNAPSHOT'
main: de.theredend2000.advancedhunt.Main
api-version: 1.13
softdepend: [PlaceholderAPI, NBTAPI, ProtocolLib, ItemsAdder]
website: https://www.spigotmc.org/resources/advancedtreasurehunt.109085/
authors: [ TheRedEnd2000, GrafterCrafter ]

permissions:
  AdvancedHunt.command.reset:
    description: "Resets all plugin data"
  AdvancedHunt.command.settings:
    description: "Shows and allows for updating of config settings"
  AdvancedHunt.command.reload:
    description: "Reload plugin"
  AdvancedHunt.command.commands:
    description: "Reward commands that are ran when a player finds a treasure"
  AdvancedHunt.command.place:
    description: "Allow a player to enter and exit treasure placing mode"
  AdvancedHunt.command.import:
    description: "Import a player head that is help in the main hand"
  AdvancedHunt.command.show:
    description: "Show the location of nearby placed treasures using glowing armor stands"
  AdvancedHunt.command.list:
    description: "List all placed treasures for the selected collection"

  AdvancedHunt.command.help:
    description: "Show a list of possible commands with short descriptions"
  AdvancedHunt.command.collection:
    description: "Change selected collection"
  AdvancedHunt.command.progress:
    description: "Shows the progress for treasures found"
  AdvancedHunt.command.leaderboard:
    description: "Shows the leaderboard for the treasure hunt"
  AdvancedHunt.command.hint:
    description: "Shows a hint in the form of coordinates of a nearby treasure that the player has not found yet"


  AdvancedHunt.BreakTreasure:
    description: ""
  AdvancedHunt.PlaceTreasure:
    description: ""
  AdvancedHunt.IgnoreCooldown:
    description: ""
  AdvancedHunt.ChangeCollections:
    description: ""
  AdvancedHunt.CreateCollection:
    description: ""
  AdvancedHunt.OpenRewards:
    description: ""
  AdvancedHunt.FindTreasures:
    description: ""

  AdvancedHunt.group.admin:
    description: "Contains all essential admin permissions"
    default: op
    children:
      AdvancedHunt.command.reload: true
      AdvancedHunt.command.reset: true
      AdvancedHunt.command.settings: true
      AdvancedHunt.command.commands: true
      AdvancedHunt.command.place: true
      AdvancedHunt.command.show: true
      AdvancedHunt.command.list: true
      AdvancedHunt.command.import: true

      AdvancedHunt.BreakTreasure: true
      AdvancedHunt.PlaceTreasure: true
      AdvancedHunt.ChangeCollections: true
      AdvancedHunt.CreateCollection: true
      AdvancedHunt.OpenRewards: true

      AdvancedHunt.group.default: true

  AdvancedHunt.group.default:
    description: "Contains all essential default permissions"
    default: true
    children:
      AdvancedHunt.command.help: true
      AdvancedHunt.command.collection: true
      AdvancedHunt.command.progress: true
      AdvancedHunt.command.leaderboard: true
      AdvancedHunt.command.hint: true
      AdvancedHunt.FindTreasures: true